"""Build the packet constraints and write them as a SystemVerilog package.

Run: python3 packet_problem.py [output.sv]   (default: packet_problem_pkg.sv)
"""
import base64
import sys

from dv_solve.builder import SolveProblemBuilder
from dv_solve.problem import BIN_BAND, BIN_EQ, BIN_LT, BIN_LTE, BIN_ADD, BIN_NEQ, BIN_GT, BIN_OR

ADDR, LEN, KIND = 0, 1, 2

b = SolveProblemBuilder()
b.add_var(ADDR, width=32, is_signed=False, lo=0, hi=0xFFFF_FFFF)
b.add_var(LEN, width=8, is_signed=False, lo=0, hi=0xFF)
b.add_var(KIND, width=4, is_signed=False, lo=0, hi=0xF)

addr, ln, kind = b.expr_var(ADDR), b.expr_var(LEN), b.expr_var(KIND)
c = b.expr_const

# addr[1:0] == 0: word aligned
b.add_constraint(b.expr_binary(BIN_EQ, b.expr_binary(BIN_BAND, addr, c(3)), c(0)))
# len inside {[1:16]}
b.add_constraint(b.expr_in_range(ln, c(1), c(16)))
# the packet lies inside the first 4 KB
b.add_constraint(b.expr_binary(BIN_LT, addr, c(0x1000)))
b.add_constraint(b.expr_binary(BIN_LTE, b.expr_binary(BIN_ADD, addr, ln), c(0x1000)))
# kind != 0;  (kind == 7) -> (len > 8), written as kind != 7 || len > 8
b.add_constraint(b.expr_binary(BIN_NEQ, kind, c(0)))
b.add_constraint(b.expr_binary(BIN_OR, b.expr_binary(BIN_NEQ, kind, c(7)),
                               b.expr_binary(BIN_GT, ln, c(8))))

problem = base64.b64encode(b.finalize_bytes()).decode("ascii")

out = sys.argv[1] if len(sys.argv) > 1 else "packet_problem_pkg.sv"
with open(out, "w") as f:
    f.write("// Generated by packet_problem.py -- do not edit.\n"
            "package packet_problem_pkg;\n"
            f'  localparam string PROBLEM = "{problem}";\n'
            f"  localparam int ADDR = {ADDR}, LEN = {LEN}, KIND = {KIND};\n"
            "endpackage\n")
